server:
  port: 5555
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKASERVER_URI}

spring:
  cloud:
    config:
      uri : ${GUTENBERG_CONFIG_URI}
  
    gateway:
      routes:
      - id: books
        uri: http://localhost:8081
        predicates:
        - Path=/book/**
        filters:
        - StripPrefix=1 
      - id: users
        uri: http://localhost:8084
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1 
      - id: orders
        uri: http://localhost:8083
        predicates:
        - Path=/order/**
        filters:
        - StripPrefix=1 
      - id: reviews
        uri: http://localhost:8082
        predicates:
        - Path=/review/**
        filters:
        - StripPrefix=1 
        
      httpclient:
        connect-timeout: 10000
        response-timeout: 10s
        
        